# Genera las 9 tomas con Genjutsu motion_control. Uso: python3 run_batch.py 480p
import subprocess, sys, json, re, os, concurrent.futures as cf
RES = sys.argv[1]; ONLY = sys.argv[2:] or [str(i) for i in range(1,10)]
up = dict(l.split() for l in open('uploads.txt') if l.strip())
REGINA = [os.environ.get("SHEET", "29aa9915-ea3d-4333-8824-e8ba71f9d1c6")] + ([] if os.environ.get("SOLO_HOJA") else ["d66a52ab-85db-4040-a350-0f33ec2e037d"])
BG = {10:"31463d10-3a29-4893-80d6-92e821809af7", 9:"05515e79-aed4-4065-ab26-a3aa5eab646b", 8:"bf929aab-e380-4701-96f8-07b38ef63b69", 7:"1448e717-03a5-4332-9ced-778c4e7e9409", 6:"40e157f5-e540-4fec-9838-9d0db7d549a9", 5:"40e157f5-e540-4fec-9838-9d0db7d549a9", 1:"09c89be8-6931-4e6c-b530-245e8a9f577b", 2:"d26067be-0a32-451b-ba2c-5f1d0e751708", 3:"575472d2-d227-4623-afb6-862e529027db", 4:"035bc418-56c7-48de-8dde-1e35d367c96b"}
ORDEN = {1:1, 2:4, 3:2, 4:1, 5:3, 6:2, 7:1, 8:3, 9:2}   # rotación 1-3-2
PERSONA = ("Replace the woman in the video with Regina, the exact same person from the character reference sheet, the portrait and the photo; keep her identity 100% consistent with the references and do not change her face, age, skin tone, hair or features: same face, long straight dark-brown hair with center part, "
  "thick eyebrows, light freckles, small gold hoop earrings, gold chain bracelet, cream ribbed off-the-shoulder short-sleeve top, high-waisted black wide-leg tailored trousers that fall straight and full-length to the floor with a clean finished hem resting over the heels (no cuffs, no rolled or folded hem, no turn-ups), and black pointed-toe heels. "
  "Regina's outfit is exactly as in the character sheet and must not be deformed or modified in any way: the trousers keep their straight full length to the shoes with no cuffs or folded hem, the off-the-shoulder top keeps its shape. Regina's hair is exactly as in the character sheet: long, sleek, straight dark-brown hair worn DOWN and loose with a center part, falling in front over both shoulders down to the chest; NOT tied, NOT pulled back, NOT tucked behind the ears or shoulders, no ponytail, no bun, no updo. Regina performs exactly the same body motion, hand gestures, head movements and lip movements as the original woman, speaking to camera at the same position and size in frame, " + ("medium shot framed from just above the knees up, exactly like the source video framing. " if os.environ.get('MEDIO') else "full body standing. "))
LUGAR = {
 10: "Replace the flat green background with the exact view of the location reference photograph, keeping its framing, very low camera height, perspective and composition exactly as it is (no reframing, no redesign): the clubhouse with the horizontal wood-slat roof and the glass walls, the travertine wall, the planting beds, the grey concrete walkway, and the few out-of-focus lavender stems right in front of the lens at the bottom. "
    "Regina stands ON THE GREY CONCRETE WALKWAY, both heels firmly on the concrete (never on grass, soil or plants), full body, at natural human scale for a camera about 50 cm above the ground looking slightly up, in the same place and size as in the source video; the blurred lavender stems stay in front of her legs at the bottom of the frame. "
    "Light is plain natural sunlight of a clear afternoon at 5 pm, exactly the light of the photo: neutral daylight color, the sun to the right and slightly behind her, lighting the right side of her hair and shoulder, the rest of her in soft natural daylight bounced from the concrete; her own crisp natural shadow falls on the concrete in the same direction as the other shadows; exposure, contrast, color, sharpness and grain on her match the photo exactly, real matte skin with pores and freckles. No golden glow, no rim-light halo, no lens flare, no cinematic grading. "
    "Natural life: the shrubs, grasses and the lavender stems move gently in a light breeze, her hair moves very slightly; subtle and believable. Static camera. ",
 9: "Replace the flat green background with the exact view of the location reference photograph, keeping its framing, low camera height, design and composition exactly as it is (no reframing, no redesign): the clubhouse pavilion with the wood-slat roof and glowing glass walls, the concrete path with the benches and bollard lights, the black sports-court fence, the leafy tree on the right lit by the sun, and the lavender and magenta flowers very close to the lens, soft and out of focus at the bottom of the frame. "
    "American shot from mid-thigh up: Regina stands on the concrete path behind the blurred lavender in the foreground, at natural human scale, exactly as framed in the source video; the out-of-focus lavender and flowers stay IN FRONT of her at the bottom of the frame. Real 5 pm light, exactly as in the photo: the low warm golden sun comes from the right, behind the tree, giving Regina a soft warm golden edge light on the right side of her hair, cheek and shoulder, while her face and front are lit softly by warm light bouncing off the bright concrete, with natural falloff, real skin texture with pores and light freckles, matte natural skin, catchlights in her eyes; exposure and color temperature on her match the photo. "
    "Natural life: the leaves and branches of the tree sway gently and continuously in a light breeze, light flickers through the leaves, the lavender and flowers in the foreground and the shrubs move softly with the breeze; subtle and believable. ",
 8: "Replace the flat green background with the exact view of the location reference photograph, keeping its framing, low camera height, design and composition exactly as it is (no reframing, no redesign): the stone paver path of the park, the central flowering tree, the concrete chess tables, the magenta bougainvillea on both sides, the large leafy trees and the golden late-afternoon sky. "
    "American shot from mid-thigh up, camera at waist height looking very slightly up at Regina, who stands on the stone path in the foreground at natural human scale, exactly as framed in the source video. Respect the light of the photo exactly: the low golden sun is behind the trees in the background, so Regina receives a soft natural warm backlight on the edges of her hair and shoulders, and her face and front are lit softly by warm light bouncing off the bright limestone pavers, with natural falloff, real skin texture with pores and light freckles, matte natural skin, catchlights in her eyes; the exposure and color temperature on her match the photo. "
    "Natural life in the park: the leaves and branches of the trees sway gently and continuously in a light breeze, light flickers softly through the leaves, the bougainvillea and flowering shrubs move softly; subtle and believable. ",
 7: "Replace the flat green background with the exact view of the location reference photograph, keeping its framing, camera angle, design and composition exactly as it is (no reframing, no redesign): the elliptical pocket park with the stepped light-beige stone paver path, the lawns, the white flowering shrubs, the magenta bougainvillea bushes, the concrete chess tables, the trees, the river-rock gravel, the white curb and the warm hazy sky. "
    "Regina stands at ground level ON the stone paver path in the foreground, full body, both heels planted on the pavers, at a natural human scale for the camera height. Respect the light of the photo exactly: soft warm late-afternoon low sun, warm highlights on her skin, top and hair matching the warm highlights on the pavers, gentle natural falloff, and her own soft contact shadow under her heels plus a long soft cast shadow on the pavers in the same direction and softness as the shadows of the plants and chess tables. No rim light, no halo, no glow. "
    "Natural life in the park: the leaves and branches of the trees sway gently and continuously in a light breeze, the flowering shrubs and bougainvillea move softly, the leaf shadows shift slightly on the pavers; subtle, believable, never exaggerated. ",
 1: "Replace the flat green background with the real showroom lounge from the location reference photo: warm plaster curved walls, wooden lounge chairs, tropical plants, sheer white curtains with soft late-afternoon sunlight and leaf shadows on the polished concrete floor. "
    "Regina is fully integrated: warm window light on her skin and clothes, matching color temperature, soft shadows under her heels. "
    "In the background a man and a woman sit on the wooden lounge chairs, clearly visible beside Regina, having a real relaxed conversation the whole time: they turn their heads toward each other, take turns talking with natural mouth movement, nod, smile and laugh lightly, the woman gestures with her hands while explaining, the man leans forward and rests his forearms on his knees, then leans back, shifting their posture naturally. Their motion is continuous, subtle and believable, never frozen. The curtains sway gently and the leaf shadows move softly on the floor. ",
 2: "Replace the flat green background with the real showroom room from the location reference photo: warm plaster walls, the long wooden table with illuminated maps, the white quote on the wall, the flat screen on the left, recessed ceiling lights and the curving inlaid lines on the concrete floor. "
    "Regina is fully integrated: warm overhead downlight on her skin and clothes, matching color temperature, soft shadows under her heels. "
    "Subtle life in the room without anyone walking: a sales advisor stands at the map table pointing at the plans while a couple stands beside the table looking and nodding, small natural movements only. ",
 4: "Replace the flat green background with the exact view of the location reference photograph, keeping its framing, camera angle, architecture and composition exactly as it is (no reframing, no redesign): the travertine cantilevered roof, the tall column of horizontal wooden slats on the right with the existing vertical white lettering 'montessa' (m-o-n-t-e-s-s-a, double s), the beige perforated gates, the lavender and boulders, the tree, the white SUV and the golden cloudy sky. "
    "Around 5 pm, the sun is behind the camera to the left, out of frame. Regina stands on the driveway in front of the portico, left of the wooden column, in a medium shot with the portico softly out of focus behind her (real lens depth of field, background about 15 meters away). The same sun lights her naturally from the front-left: warm-neutral sunlight on the left side of her face, neck and arms, gentle natural falloff and soft shadow on her right side, a small catchlight in her eyes, slight squint-free relaxed expression, real skin texture with pores and fine peach fuzz, individual hair strands moving slightly in the breeze; the light on her matches the light on the facade exactly. No rim light, no backlight glow, no halo. A steady, gusty breeze: the lavender and tall grasses at the base of the column bend and sway clearly, leaf shadows from trees out of frame flicker and move on the wooden column and the ground, and Regina's hair moves slightly with the breeze. The white SUV is seen from behind and drives forward, away from the camera, entering through the open gate into the community and getting smaller as it goes in; it never reverses and never moves toward the camera. Keep only the existing 'montessa' sign; do not add any other text. ",
 5: "Match EXACTLY the lighting reference frame (the last reference image): the same camera framing and distance, the same warm golden front sunlight on Regina's face and body, the same brightness and color temperature, and the same long shadows on the asphalt; ignore the trousers in that frame. Replace the flat green background with the exact view of the location reference photograph, keeping its framing, camera angle, architecture and composition exactly as it is (no reframing, no redesign): the travertine cantilevered roof, the tall column of horizontal wooden slats on the right with the existing vertical white lettering 'montessa' (m-o-n-t-e-s-s-a, double s), the beige perforated gates, the lavender and boulders, the tree, the white SUV and the warm evening sky. "
    "Warm golden late-afternoon sun coming from the FRONT, from behind the camera, the same sun that lights the facade and casts the tree shadows on the wooden column; there is no sun behind Regina. Regina stands on the dry asphalt driveway in the foreground, left of the wooden column, full body, lit from the front by that warm golden sunlight: warm glow on her face, chest, arms and clothes, natural soft shadows under her chin and on the folds of her trousers, catchlights in her eyes, real skin texture with pores, fine hair strands; her own shadow falls BEHIND her on the asphalt, away from the camera toward the portico, matching the direction of all other shadows. No rim light, no backlight glow, no halo, no lens flare. "
    "A very gentle, subtle breeze: the tree leaves move only slightly and softly, its dappled shadows on the wooden column shift just a little, the lavender sways gently, Regina's hair barely moves. "
    "The beige perforated sliding gate in front of the white SUV opens very slowly and smoothly to the side, with a natural steady mechanical motion that lasts the whole clip; the white SUV, seen from behind, waits calmly in front of the gate and may only begin to roll forward very slowly at the very end; it never reverses, never moves toward the camera and never passes through the gate while it is closed. "
    "Keep only the existing 'montessa' sign; do not add any other text. ",
 6: "Replace the flat green background with the exact view of the location reference photograph, keeping its architecture and composition (no redesign): the travertine cantilevered roof, the tall column of horizontal wooden slats with the existing vertical white lettering 'montessa' (m-o-n-t-e-s-s-a, double s), the beige perforated gates, the lavender and boulders, the tree, the white SUV and the warm evening sky. "
    "Warm golden late-afternoon sun coming from the FRONT, from behind the camera, the same sun that lights the facade and casts the tree shadows on the wooden column; there is no sun behind Regina. Regina stands on the driveway in front of the portico, left of the wooden column, in a medium shot with the portico softly out of focus behind her (real lens depth of field). "
    "She is lit from the front by that same warm golden sunlight: warm glow on her face, neck, shoulders and arms, gentle natural shadow under her chin, catchlights in her eyes, natural MATTE skin with visible real texture, pores, fine peach fuzz and light freckles, absolutely no glossy, oily, waxy or glowing skin, no beauty filter, no airbrushed look; fine hair strands; the warm golden-hour light on her matches the light on the facade exactly, as if filmed facing the setting sun. No rim light, no backlight glow, no halo, no lens flare. "
    "A light breeze: the branches and leaves of the tree sway gently and continuously, the leaf shadows on the wooden column move with them, the lavender moves softly, her hair barely moves. The white SUV waits calmly in front of the gate. "
    "Keep only the existing 'montessa' sign; do not add any other text. ",
 3: "Replace the flat green background with the real showroom hall from the location reference photo: oval recessed ceiling with warm downlights, the large sculpted wooden terrain model in the center, lounge chairs, plants and tall windows with daylight on the right. "
    "Regina is fully integrated: warm ambient downlight mixed with soft window light on her skin and clothes, matching color temperature, soft shadows under her heels. "
    "Subtle life in the room without anyone walking: two people stand at the wooden terrain model looking at it and talking, one person sits in a lounge chair near the windows, small natural movements only. ",
}
import os
LOOK = ("Cinematic look, shot on ARRI Alexa 35 with an ARRI Signature Prime 50mm lens at T2, ARRI color science with natural skin tones, soft highlight roll-off on the brightest areas, gentle filmic contrast with slightly lifted blacks, motivated natural light consistent with the location, shallow depth of field with the background softly out of focus and creamy bokeh, subtle fine film grain. " if os.environ.get('ARRI','1') != '0' else "")  # ARRI siempre
CIERRE = ("No people walking or crossing the frame close to Regina. Hyperrealistic, real cinema camera, static locked-off camera, natural depth of field with the background slightly soft. "
  "Absolutely no text, no subtitles, no captions, no on-screen words or graphics added.")
def run(i):
    i = int(i); b = int(os.environ.get('BG', ORDEN[i])); prompt = PERSONA + LUGAR[b] + LOOK + CIERRE
    extra = (["--image", os.environ["LUZ"]] if os.environ.get("LUZ") else [])
    cmd = ["higgsfield","generate","create","hf_mult_motion_control","--prompt",prompt,"--video",(up[f"clean{i}m"] if os.environ.get("MEDIO") else up.get(f"clean{i}w", up[f"clean{i}"])),
           *sum([["--image", r] for r in REGINA], []),"--image",BG[b]] + extra + ["--resolution",RES,"--wait","--wait-timeout","40m","--json"]
    out = subprocess.run(cmd, capture_output=True, text=True).stdout
    urls = [u for u in re.findall(r'"result_url":\s*"([^"]+)"', out)]
    if not urls: return f"toma{i} ERROR {out[-400:]}"
    subprocess.run(["curl","-s","-o",f"gen_{RES}_toma{i}{os.environ.get('SUF','')}.mp4",urls[0]])
    return f"toma{i} fondo{b} ok"
with cf.ThreadPoolExecutor(9) as ex:
    for r in ex.map(run, ONLY): print(r, flush=True)
